# docker-compose -f LNX-docker-compose.yml --env-file LNX.env up --build --exit-code-from app
version: '2.2'
x-net: &net
  networks:
    - main
services:
  db:
    <<: *net
    image: datajoint/mysql:${MYSQL_TAG}
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  fakeservices.datajoint.io:
    <<: *net
    image: raphaelguzman/nginx:v0.0.4
    environment:
    - ADD_db_TYPE=DATABASE
    - ADD_db_ENDPOINT=db:3306
    depends_on:
      db:
        condition: service_healthy
  app:
    <<: *net
    environment:
    - DISPLAY
    - MATLAB_LICENSE
    - MATLAB_USER
    - DJ_HOST=fakeservices.datajoint.io
    - DJ_USER=root
    - DJ_PASS=simple
    - DJ_TEST_HOST=fakeservices.datajoint.io
    - DJ_TEST_USER=datajoint
    - DJ_TEST_PASSWORD=datajoint
    image: raphaelguzman/matlab:${MATLAB_VERSION}-MIN
    depends_on:
      fakeservices.datajoint.io:
        condition: service_healthy
    user: ${MATLAB_UID}:${MATLAB_GID}
    working_dir: /src
    command: > 
      /bin/bash -c "
        matlab -nodisplay -r \"\
            res=run(tests.Main);\
            disp(res);\
            if all([res.Passed])  exit, else exit(1), end;\
          \";
      "
    mac_address: $MATLAB_HOSTID
    volumes:
      - .:/src
networks:
  main: